### ISSUE TITLE
How can I retrive the pos data in showmap fuction?

### ISSUE THREAD

**Issue by dotku** [matt-west/simple-geolocation-example#1]
What I try to do is

pos = getGeoPostion(); // this will retrive the pos info from API
showMap(pos) ; // this will draw the map

The problem is it seems Geolocation.getCurrentPosition() is runing in ajax way, so showMap(pos) would always retrive a 'undefined'.

**Comment by matt-west** [comment]
@dotku That's correct. The `navigator.geolocation.getCurrentPosition()` method needs to be passed a callback function that handles the result. For example:

```
navigator.geolocation.getCurrentPosition(function(position) {
    var lat = position.coords.latitude;
    var lon = position.coords.longitude;

    // Show the map
    showMap(lat, lon);
});
```
